# # -*- coding: utf-8 -*-
# """train_YOLOv8.ipynb

# Automatically generated by Colab.

# Original file is located at
#     https://colab.research.google.com/drive/18Vqg01DC-lc16Ij2y1lvuX1hnDgFKnFx
# """

# from google.colab import drive
# drive.mount('/content/drive')

# !pip install roboflow

# from roboflow import Roboflow
# rf = Roboflow(api_key="MLlGMOfNaHlUhVNNMpWG")
# project = rf.workspace("ltd").project("food-ttntd")
# version = project.version(2)
# dataset = version.download("yolov8")

# !pip install ultralytics

# !wget https://github.com/ultralytics/assets/releases/download/v0.0.0/yolov8n.pt

# from ultralytics import YOLO

# model = YOLO("/content/yolov8n.pt")

# model.train(data='/content/FOOD-2/data.yaml', epochs=100, imgsz=640, batch=16)

# model.val()

# import matplotlib.pyplot as plt
# import matplotlib.image as mpimg

# # Đường dẫn hình ảnh
# image_path = "/content/2.jpg"

# # Đọc và hiển thị hình ảnh
# img = mpimg.imread(image_path)
# plt.imshow(img)
# plt.axis('off')  # Tắt hiển thị trục
# plt.show()

# # Dự đoán trên tập kiểm tra
# # results = model('/content/FOOD-2/test/images')
# # Dự đoán trên một hình ảnh cụ thể
# image_path = "/content/2.jpg"  # Đường dẫn đến hình ảnh bạn muốn nhận diện
# results = model(image_path)

# model.save('/content/drive/MyDrive/app/final_model_1.pt')